version: "3.2"
services:
  rabbitmq:
  # TODO: configure username/password
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/Data/MovieCruncher/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/Data/MovieCruncher/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - moviecruncher
  
  redis:
    image: redis:latest
    container_name: moviecrunch_redis
    ports:
      - "6379:6379"
    volumes:
      - ./dev/redis:/data 
    networks:
      - moviecruncher

networks:
  moviecruncher:
    driver: bridge