# TODO: having trouble parsing names with dashes or underscores, investigate further
messaging:
  host: "localhost"
  port: 5672

dataingestion:
  queuename: "data_ingestion_queue"

api:
  queuename: "api_queue"